name: ptwcode_map
description: A versatile, customizable and configurable flutter map.
version: 1.0.1
repository: https://github.com/alidev0/ptwcode_map

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  path_provider: ^2.0.14
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
