name: ptwcode_map
description: A flutter map that is configurable to use the tile provider you want.

version: 1.0.5
repository: https://github.com/alidev0/ptwcode_map

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
